# Generated by Django 4.1.4 on 2023-01-02 08:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('name', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('name', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('name', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('topic', models.ManyToManyField(blank=True, to='exampleproject.topic')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('name', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleproject.branch')),
                ('units', models.ManyToManyField(blank=True, to='exampleproject.unit')),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('branches', models.ManyToManyField(blank=True, to='exampleproject.branch')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleproject.classproject')),
            ],
        ),
    ]
