# Generated by Django 4.1.4 on 2023-01-02 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0002_branch_topic_unit_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='unit',
            name='weightage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
