# Generated by Django 4.1.4 on 2023-01-02 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0003_topic_vote_total_unit_weightage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='vote_total',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='unit',
            name='weightage',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
