# Generated by Django 4.1.4 on 2023-01-04 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0006_timetable_end_date_timetable_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
