# Generated by Django 4.1.4 on 2023-01-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0009_alter_timetable_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timetable',
            new_name='Timetable1',
        ),
    ]
