# Generated by Django 4.1.4 on 2023-01-04 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0010_rename_timetable_timetable1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable1',
            name='created',
        ),
        migrations.AddField(
            model_name='timetable1',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timetable1',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timetable1',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
