# Generated by Django 4.1.4 on 2023-01-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0011_remove_timetable1_created_timetable1_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable1',
            name='end_date',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='timetable1',
            name='start_date',
            field=models.CharField(max_length=400),
        ),
    ]
