# Generated by Django 4.1.4 on 2023-01-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0012_alter_timetable1_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_date', models.CharField(max_length=400)),
                ('custom_hrs', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
