# Generated by Django 4.1.4 on 2023-01-05 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0014_remove_timetable1_units_timetable3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_hrs', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='timetable1',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
