# Generated by Django 4.1.4 on 2023-01-05 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0017_alter_timetable1_id_alter_timetable2_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable1',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='timetable1',
            name='subjects',
            field=models.ManyToManyField(to='exampleproject.subject'),
        ),
        migrations.AlterField(
            model_name='timetable1',
            name='weekday_hrs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timetable1',
            name='weekend_hrs',
            field=models.IntegerField(default=0),
        ),
    ]
