# Generated by Django 4.1.4 on 2023-01-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0018_alter_timetable1_id_alter_timetable1_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable1',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timetable1',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='exampleproject.subject'),
        ),
        migrations.AlterField(
            model_name='timetable1',
            name='weekday_hrs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='timetable1',
            name='weekend_hrs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
