# Generated by Django 4.1.4 on 2023-01-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0019_alter_timetable1_id_alter_timetable1_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable1',
            name='num_subjects',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
