# Generated by Django 4.1.4 on 2023-01-05 22:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0020_timetable1_num_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='sumn',
            fields=[
                ('name', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
