# Generated by Django 4.1.4 on 2023-01-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0021_sumn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable4',
        ),
        migrations.RemoveField(
            model_name='sumn',
            name='name',
        ),
        migrations.AddField(
            model_name='sumn',
            name='units',
            field=models.ManyToManyField(blank=True, to='exampleproject.unit'),
        ),
    ]
