# Generated by Django 4.1.4 on 2023-01-06 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0022_delete_timetable4_remove_sumn_name_sumn_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjecthrs',
            fields=[
                ('subject_hrs', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
