# Generated by Django 4.1.4 on 2023-01-06 06:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0023_subjecthrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable1',
            name='subjects',
        ),
        migrations.CreateModel(
            name='whatsubjects',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subjects', models.ManyToManyField(blank=True, to='exampleproject.subject')),
            ],
        ),
    ]
