# Generated by Django 4.1.5 on 2023-01-06 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0025_subjecthrs_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTT',
            fields=[
                ('zefile', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
